version: '3'
services:
  redis:
    image: redis
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - app-network

  app:
    build: .
    container_name: springboot-app
    ports:
      - "8080:8080"
#    environment:
#      - SPRING_REDIS_HOST=redis
#      - SPRING_REDIS_PORT=6379
    depends_on:
      - redis
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
